name: gradual_stepper
version: 1.0.0
description: >-
  A flutter stepper widget for selecting values in natural ways.
  Ideal for amount selection.
homepage: https://github.com/moustaphachadly/gradual_stepper.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
